ATS.WebUi/Areas/Employee/Controllers/TemplateVacancyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RootModels = ATS.WebUi.Models;
using BECommon = ATS.BusinessEntity.Common;
using BEClient = ATS.BusinessEntity;
using ATSCommon = ATS.WebUi.Common;
using BESrp = ATS.BusinessEntity.SRPEntity;
using ATS.WebUi.Models;
using BLClient = ATS.BusinessLogic;
using BLCommon = ATS.BusinessLogic.Common;

namespace ATS.WebUi.Areas.Employee.Controllers
{
    public partial class TemplateVacancyController : ATS.WebUi.Controllers.AreaBaseController
    {
        #region Private Member
        private Guid _CurrentClientId;
        private Guid _CurrentLanguageId;
        private Guid _UserId;
        private BLClient.TVacAction _ObjTVacAction;
        private BLClient.TVacancyRoundAction _ObjTVacancyRoundAction;
        private BLClient.TVacQueCatAction _ObjTVacQueCatAction;
        private BLClient.TVacReviewMemberAction _ObjTVacReviewMemberAction;
        private BESrp.DynamicSRP<BEClient.TVac> _objTVac;
        private BLClient.TVacQueAction _ObjTVacQueAction;
        private BLClient.VacancyAction _objVacancyAction;
        BLCommon.DrpStringMappingAction _DrpdownStringMappingAction;

        private BESrp.DynamicSRP<List<BEClient.TVac>> _ObjTvacList;
        #endregion

        #region Get Object from Private
        private BLClient.TVacAction ObjTVacAction
        {
            get
            {
                if (_ObjTVacAction == null)
                {
                    _ObjTVacAction = new BLClient.TVacAction(_CurrentClientId, true);
                }
                return _ObjTVacAction;
            }

        }

        private BLClient.TVacQueCatAction ObjTVacQueCatAction
        {
            get
            {
                if (_ObjTVacQueCatAction == null)
                {
                    _ObjTVacQueCatAction = new BLClient.TVacQueCatAction(_CurrentClientId);
                }
                return _ObjTVacQueCatAction;
            }
        }

        private BLClient.TVacancyRoundAction ObjTVacancyRoundAction
        {
            get
            {
                if (_ObjTVacancyRoundAction == null)
                {
                    _ObjTVacancyRoundAction = new BLClient.TVacancyRoundAction(_CurrentClientId);
                }
                return _ObjTVacancyRoundAction;
            }
        }

        private BLClient.TVacReviewMemberAction ObjTVacReviewMemberAction
        {
            get
            {
                if (_ObjTVacReviewMemberAction == null)
                {
                    _ObjTVacReviewMemberAction = new BLClient.TVacReviewMemberAction(_CurrentClientId);
                }
                return _ObjTVacReviewMemberAction;
            }
        }

        private BLClient.TVacQueAction ObjTVacQueAction
        {
            get
            {
                if (_ObjTVacQueAction == null)
                {
                    _ObjTVacQueAction = new BLClient.TVacQueAction(_CurrentClientId, true);
                }
                return _ObjTVacQueAction;
            }
        }

        #endregion

        #region On Authentication
        protected override void OnAuthorization(AuthorizationContext filterContext)
        {
            base.OnAuthorization(filterContext);
            if (base.CurrentClient != null && Common.CurrentSession.Instance.VerifiedUser != null)
            {
                if (Common.CurrentSession.Instance.VerifiedUser.ManageCompanySetup == false)
                {
                    TempData["KeyMsg"] = ATSCommon.CommonFunctions.NonAuthoriseduser();
                    filterContext.Result = new RedirectResult(Url.Action(ATSCommon.Constants.DEFAULT_REDIRECT_EMPLOYEE_ACTION, ATSCommon.Constants.DEFAULT_REDIRECT_EMPLOYEE_CONTROLLER, new { @KeyMsg = ATSCommon.CommonFunctions.NonAuthoriseduser() }));
                }
                _CurrentClientId = base.CurrentClient.ClientId;
                _CurrentLanguageId = base.CurrentClient.CurrentLanguageId;
                _UserId = ATSCommon.CurrentSession.Instance.UserId;

                _ObjTvacList = new BESrp.DynamicSRP<List<BEClient.TVac>>();

                _ObjTvacList.UserPermissionWithScope = ObjTVacAction.ListUserPermissionWithScope;

                if (ATSCommon.CurrentSession.Instance.VerifiedUser.SecurityRoles.Where(x => x.AtsSecurityRole == BEClient.ATSSecurityRole.Candidate).Count() > 0)
                {
                    filterContext.Result = new RedirectResult(Url.Action(ATSCommon.Constants.DEFAULT_REDIRECT_CANDIDATE_ACTION, ATSCommon.Constants.DEFAULT_REDIRECT_CANDIDATE_CONTROLLER, new { area = ATSCommon.Constants.AREA_CANDIDATE }));
                }
                if (filterContext.ActionDescriptor.ActionName == "View" && filterContext.RouteData.Values.Keys.Count() == 2)
                {
                    if (_ObjTvacList.UserPermissionWithScope.Where(x => x.PermissionType.Contains(BEClient.ATSPermissionType.Create)).Count() <= 0)
                    {
                        TempData["KeyMsg"] = ATSCommon.CommonFunctions.NonAuthoriseduser();
                        filterContext.Result = new RedirectResult(Url.Action(ATSCommon.Constants.DEFAULT_REDIRECT_EMPLOYEE_ACTION, ATSCommon.Constants.DEFAULT_REDIRECT_EMPLOYEE_CONTROLLER, new { @KeyMsg = ATSCommon.CommonFunctions.NonAuthoriseduser() }));
                    }
                }
            }
        }
        #endregion

        public ActionResult Index(string ordinal)
        {
            bool isEdit = false;
            bool IsConsiderToCheck = true;
            BEClient.PageMode objPageMode = BEClient.PageMode.View;
            RootModels.BreadScrumbModel<BESrp.DynamicSRP<List<BEClient.TVac>>> _objTVac = new BreadScrumbModel<BESrp.DynamicSRP<List<BEClient.TVac>>>();
            _ObjTvacList.obj = GetVacancyTemplateByRights();
            _objTVac.obj = _ObjTvacList;
            _objTVac.DisplayName = BEClient.Common.CompanySetupMenu.CSMNU_VACANCYTEMPLATES;
            _objTVac.ToolTip = "Opportunity Templates";
            _objTVac.obj.UserPermissionWithScope = ObjTVacAction.ListUserPermissionWithScope;
            ViewBag.QuestionPermission = ObjTVacAction.ListUserPermissionWithScope;
            NavIndex(ordinal);
            return View(_objTVac);
        }

        private void DropDownLists(string pVacancyState, BEClient.ATSPermissionType PermissionType, Guid divisionId, string callMethod)
        {
            try
            {

            }
            catch
            {
                throw;
            }
        }

        [HttpGet]
        public JsonResult GetNewTVac()
        {
            String Message = String.Empty;
            bool IsError = false;
            String Data = String.Empty;
            try
            {
                BESrp.DynamicSRP<BEClient.TVac> _objTVacSrp = new BESrp.DynamicSRP<BEClient.TVac>();
                _objTVacSrp.obj = new BEClient.TVac();
                _objTVacSrp.obj.Name = "New Template";
                BEClient.PageMode objPageMode = BEClient.PageMode.Create;
                ViewBag.PageMode = objPageMode;
                _objTVacSrp.obj.EntityLanguageList = ATSCommon.CommonFunctions.MultiLanguage();
                ViewBag.QuestionPermission = ObjTVacAction.ListUserPermissionWithScope;
                DropDownForTVac(BEClient.ATSPermissionType.Create, "Create", Guid.Empty);
                Data = base.RenderRazorViewToString("Shared/_TVacCreate", _objTVacSrp);
            }
            catch (Exception ex)
            {
                Message = ex.Message;
                IsError = true;
            }

            return base.GetJson(base.GetJsonContent(IsError, null, String.Empty, Data), JsonRequestBehavior.AllowGet);
        }
        #region CRUD Operation

        [HttpPost]
        public JsonResult CRUTVac(BESrp.DynamicSRP<BEClient.TVac> objTVac)
        {
            String Message = String.Empty;
            bool IsError = false;
            String Data = String.Empty;
            bool _isRecordExists = false;
            try
            {
                BEClient.PageMode ObjPageMode = BEClient.PageMode.View;
                string ErrorMessage = ServerValidation(ref objTVac);
                if (!String.IsNullOrEmpty(ErrorMessage))
                {
                    Exception ex = new Exception(ErrorMessage);
                    throw ex;
                }
                if (objTVac.obj.TVacId != Guid.Empty)
                    _isRecordExists = ObjTVacAction.IsRecordExists(objTVac.obj.TVacId);
                if (_isRecordExists)
                {
                    #region Update Record
                    bool IsrecordUpdated = ObjTVacAction.UpdateGrantTVac(objTVac.obj);
                    if (IsrecordUpdated)
                    {
                        IsError = false;
                        Message = "Updated Successfully";
                    }
                    #endregion
                }
                else
                {
                    #region Add New Record
                    Guid NewrecordAdded = ObjTVacAction.AddGrantTVac(objTVac.obj);
                    if (!NewrecordAdded.Equals(Guid.Empty))
                    {

                        IsError = false;
                        Message = "Record Inserted Successfully";
                        objTVac.obj.TVacId = NewrecordAdded;
                    }
                    #endregion
                }
                if (objTVac != null)
                {
                    ViewBag.QuestionPermission = ObjTVacAction.ListUserPermissionWithScope;
                    ObjPageMode = BEClient.PageMode.Update;
                    Data = base.RenderRazorViewToString("Shared/_TVacAcc", objTVac.obj);
                }
            }
            catch (Exception ex)
            {
                Message = ex.Message;
                IsError = true;
            }

ATS.WebUi/Areas/Employee/Views/TemplateVacancy/Shared/ApplicationReviewProcess.cshtml
@using BEClient = ATS.BusinessEntity
@using BECommonConst = ATS.BusinessEntity.Common.CommonConstant
@using BERndAttr = ATS.BusinessEntity.RndAttrNo
@model BEClient.VacancyTemplate

@{
    var CssClass = "DisplayBlock";
    BERndAttr RndAttr = (BERndAttr)Model.objTVacancyRound.RoundAttributeNo;
    if (BERndAttr.OfferRound == RndAttr)
    {
        CssClass = "DisplayNone";
    }
}

<div class="acc-header" data-vacroundid="@Model.objTVacancyRound.TVacRndId" data-pkid="@Model.objTVacancyRound.TVacRndId" data-rndattrnoheader='@Model.objTVacancyRound.RoundAttributeNo' data-rndorderheader="@Model.objTVacancyRound.RndOrder">
    <p class="prfle-tab-head-brown" data-rndattrno='@Model.objTVacancyRound.RoundAttributeNo'>
        <span class="w50 SMW70" style="float:left;">
            <span class='Save'>@Html.LanguageLabel(BECommonConst.FRM_APP_REV_ROUND) <span class="CountRound"></span>:</span>
            <span class='lblRRName ttldblue'>@Model.objTVacancyRound.RoundType</span>
        </span>
        <span style="padding-right: 1%;padding-left: 1%;" class="ansoption">
            @if (@Model.objTVacancyRound.RndOrder == 1 && @Model.RndCnt > 1)
            {
                <span class="down onload sm-disabled"><a href='javascript:void(0);' id="OrderDown" data-url='@Url.Action("TVacRndReorder", "TemplateVacancy", new { @area = ATS.WebUi.Common.Constants.AREA_EMPLOYEE, @TVacId = Model.objTVacancyRound.TVacId, @TVacRndId = Model.objTVacancyRound.TVacRndId, @OrderDir = "Down" })' data-neworder='@Convert.ToString(Model.objTVacancyRound.RndOrder + 1)' data-id='@Model.objTVacancyRound.TVacRndId' onclick="return SetTVacRndOrder(this);"><img src="~/Content/images/down_arrow_16.png" height="13" width="13" /></a></span>
            }
            else if (@Model.objTVacancyRound.RndOrder == @Model.RndCnt && @Model.RndCnt > 1)
            {
                <span class="up onload sm-disabled"><a href='javascript:void(0);' id="OrderUp" data-url='@Url.Action("TVacRndReorder", "TemplateVacancy", new { @area = ATS.WebUi.Common.Constants.AREA_EMPLOYEE, @TVacId = Model.objTVacancyRound.TVacId, @TVacRndId = Model.objTVacancyRound.TVacRndId, @OrderDir = "Up" })' data-neworder='@Convert.ToString(Model.objTVacancyRound.RndOrder - 1)' data-id='@Model.objTVacancyRound.TVacRndId' onclick="return SetTVacRndOrder(this);"><img src="~/Content/images/up_arrow_16.png" height="13" width="13" /></a></span>
            }
            else
            {
                if (@Model.RndCnt > 1)
                {
                    <span class="up onload sm-disabled"><a href='javascript:void(0);' id="OrderUp" data-url='@Url.Action("TVacRndReorder", "TemplateVacancy", new { @area = ATS.WebUi.Common.Constants.AREA_EMPLOYEE, @TVacId = Model.objTVacancyRound.TVacId, @TVacRndId = Model.objTVacancyRound.TVacRndId, @OrderDir = "Up" })' data-neworder='@Convert.ToString(Model.objTVacancyRound.RndOrder - 1)' data-id='@Model.objTVacancyRound.TVacRndId' onclick="return SetTVacRndOrder(this);"><img src="~/Content/images/up_arrow_16.png" height="13" width="13" /></a></span>
                    <span class="down onload sm-disabled"><a href='javascript:void(0);' id="OrderDown" data-url='@Url.Action("TVacRndReorder", "TemplateVacancy", new { @area = ATS.WebUi.Common.Constants.AREA_EMPLOYEE, @TVacId = Model.objTVacancyRound.TVacId, @TVacRndId = Model.objTVacancyRound.TVacRndId, @OrderDir = "Down" })' data-neworder='@Convert.ToString(Model.objTVacancyRound.RndOrder + 1)' data-id='@Model.objTVacancyRound.TVacRndId' onclick="return SetTVacRndOrder(this);"><img src="~/Content/images/down_arrow_16.png" height="13" width="13" /></a></span>
                }
            }
            <span class="up"><a href='javascript:void(0);' id="TVacroundDelete" onclick="TemplateMyVacancy.DeleteTVacRnd(this);" data-pkid="@Model.objTVacancyRound.TVacRndId"><img src="~/Content/images/delete_16.png" height="13" width="13" /></a></span>
        </span>
        <span class="ReviewRoundWt floatright sm-disabled @CssClass">
            <span class=" ttllbrown">@Html.LanguageLabel(BECommonConst.FRM_APP_REV_WEIGHT):</span>
            <span class="lblRRWeight ttldblue">@Model.objTVacancyRound.RoundWeight</span>
        </span>
    </p>
</div>

<div class="acc-Content" name="RoundDetail" data-mode="@ViewBag.PageMode">
    <div class="AccRoundDetail" style="width:98%">

    </div>
    @Html.Partial("Shared/_SectionDone", null)
</div>

<script>
    function DeleteTVacRndConfirm(result, element) {
        if (result) {
            var _TVacRndId = $(element).attr('data-pkid')
            var _dataLink = '@Url.Action("RemoveTVacRound", "TemplateVacancy", new { TVacRoundId = "_DATAPKID_" })';
            _dataLink = _dataLink.replace("_DATAPKID_", _TVacRndId)
            $.ajax({
                url: _dataLink,
                type: "POST",
                success: function (response) {
                    var data = JSON.parse(response)
                    if (data.IsError) {
                        VacancyModel.DisplayErrorMeesage('#commonMessage', data.Message, '@ATS.WebUi.Common.Constants.JSCR_MSG_FADEOUT');
                    }
                    else {
                        var lblRoundCount = $(element).parents('.AccTVacRounds').parent().prev().find("#vacrndcnt");
                        var RndCount = lblRoundCount.text();
                        lblRoundCount.text(parseInt(RndCount) - 1);
                        var _parentAcc = $(element).parents(".innerTVac");
                        var active = _parentAcc.accordion("option", "active");
                        VacancyModel.DisplaySuccessMeesage('#commonMessage', data.Message, 3000);
                        _parentAcc.accordion("option", "active", false).accordion("refresh");
                        _parentAcc.accordion("option", "active", active);
                        $(element).parents('.AccTVacRounds').next().html('');
                        $('#addTVacRnd').show();

                    }
                }
            });
        }
    }
    function SetTVacRndOrder(element, TVacId) {
        var _ele = $(element);
        var _newrndAttr = "";
        var _currRndAttr = "";
        var _message = "";        
        _currRndAttr = $(_ele).parents('.acc-header').attr('data-rndattrnoheader');
        _newrndAttr = $(_ele).parents('.acc-header').next().next().attr('data-rndattrnoheader');
        if (_newrndAttr == 1 && _currRndAttr != 1) {
            _message = "Application Round Must be the First Round.";
            VacancyModel.DisplayErrorMeesage('#commonMessage', _message, 3000);
        }
        else if (_newrndAttr != 1 && _currRndAttr == 1) {
            _message = "Application Round Must be the First Round.";
            VacancyModel.DisplayErrorMeesage('#commonMessage', _message, 3000);
        }
        else if (_newrndAttr == 5 && (_currRndAttr == 1)) {
            _message = "Applicant Survey Round cannot be the first round and it cannot be the last round.";
            VacancyModel.DisplayErrorMeesage('#commonMessage', _message, 3000);
        }
        else if (_newrndAttr != 4 && (_currRndAttr == 4)) {
            _message = "Award Round Must be the Last Round.";
            VacancyModel.DisplayErrorMeesage('#commonMessage', _message, 3000);
        }
        else if (_currRndAttr == 5 && (_newrndAttr == 1)) {
            _message = "Applicant Survey Round cannot be the first round and it cannot be the last round.";
            VacancyModel.DisplayErrorMeesage('#commonMessage', _message, 3000);
        }
        else if (_currRndAttr == 5 && (_newrndAttr == 4)) {
            _message = "Applicant Survey Round cannot be the first round and it cannot be the last round.";
            VacancyModel.DisplayErrorMeesage('#commonMessage', _message, 3000);
        }
        else if (_newrndAttr != 4 && _currRndAttr == 4) {
            _message = "Award Round Must be the Last Round.";
            VacancyModel.DisplayErrorMeesage('#commonMessage', _message, 3000);
        }
        else if (_newrndAttr == 4 && _currRndAttr != 4) {
            _message = "Award Round Must be the Last Round.";
            VacancyModel.DisplayErrorMeesage('#commonMessage', _message, 3000);
        }
        else {
            $.get($(element).attr("data-url"), function (response) {
                var jsonData = JSON.parse(response);
                if (!jsonData.IsError) {
                    var _parentAcc = $(element).parents(".innerTVac");
                    var active = _parentAcc.accordion("option", "active");
                    _parentAcc.accordion("option", "active", false).accordion("refresh");
                    _parentAcc.accordion("option", "active", active);
                    VacancyModel.DisplaySuccessMeesage('#commonMessage', jsonData.Message, 3000);
                }
            });
        }
    }

</script>

ATS.WebUi/Areas/Employee/Views/TemplateVacancy/Shared/_ApplicationProcess.cshtml
@using BEVacancyConst = ATS.BusinessEntity.Common.VacancyConstant
@using BeCommonConst = ATS.BusinessEntity.Common.CommonConstant
@model ATS.WebUi.Models.BreadScrumbModel<ATS.BusinessEntity.SRPEntity.DynamicSRP<ATS.BusinessEntity.TVac>>

@if (Model.obj.obj.VacancyRoundList != null)
{
    foreach (var v in Model.obj.obj.VacancyRoundList)
    {
        ATS.BusinessEntity.VacancyTemplate objVacancyTemplate = new ATS.BusinessEntity.VacancyTemplate();
        objVacancyTemplate.objTVacancyRound = v;
        objVacancyTemplate.RndCnt = Model.obj.obj.RndCount;
        @Html.Partial("Shared/ApplicationReviewProcess", objVacancyTemplate)
    }
}

ATS.WebUi/Areas/Employee/Views/TemplateVacancy/Shared/_BtnAddTVacRnd.cshtml
@using BeCommonConst = ATS.BusinessEntity.Common.CommonConstant

<div class="acc-action">
    <a title="" id="addTVacRnd" href='javascript:void(0);' data-url="@Url.Action("GetNewTVacRnd", "TemplateVacancy", new { @area = ATS.WebUi.Common.Constants.AREA_EMPLOYEE, @TVacId = Model.obj.TVacId })" class="btn CaseUpper">@Html.LanguageLabel(BeCommonConst.FRM_APP_REV_ADD)</a>
</div>

<script>
    $(function () {
        $("a#addTVacRnd").tooltip({
            track: false,
            open: function (event, ui) {
                setTimeout(function () {
                    $(ui.tooltip).hide('toggle');
                }, 4000);
            },
            position: { my: "left+175 top+5", at: "left top", collision: "flipfit" },
            content: function (callback) {
                callback("connecting......");
                var _Link = '@Url.Action("GetARPHint", "MyVacancy")';
                $.ajax({
                    url: _Link,
                    global: false,
                    success: function (response) {
                        response = JSON.parse(response);
                        if (!response.IsError) {
                            $(this).removeAttr("title");
                            if ($.trim(response.Data) != "") {
                                $(this).attr("title", "");
                                callback(response.Data);
                            }
                        }
                    }
                });
            }
        });
    });
</script>

ATS.WebUi/Areas/Employee/Views/TemplateVacancy/Shared/_RoundConfig.cshtml
@model ATS.BusinessEntity.TVacancyRound
@using BECommonConstantConst = ATS.BusinessEntity.Common.CommonConstant
@using BERndAttr = ATS.BusinessEntity.RndAttrNo;

@System.Web.Optimization.Scripts.Render("~/bundles/AjaxVal")
@Html.ValidationSummary(true)
@Html.HiddenFor(m => m.TVacRndId)
@Html.HiddenFor(m => m.TVacId)
@Html.HiddenFor(m => m.AssignCandiadteToReviewerId)
@Html.HiddenFor(m => m.ReqReviewer)
@Html.HiddenFor(m => m.PromoteCandidate)
@Html.HiddenFor(m => m.AssignCandidateBatches)
@{
    int RndAttrNo = ATS.WebUi.Common.CommonFunctions.GetAttributesNoByRndTypeId(Model.RndTypeId);
    BERndAttr RndAttr = (BERndAttr)RndAttrNo;
    ViewBag.RndAttr = RndAttr;
}
<div class="vacancy-Details" data-tvacrndconfigid="@Model.TVacRndId">
    <div class="vacancy-quest-box">
        <div class="std_width">
            <div class="width-62">
                @Html.LanguageLabelFor(m => m.RndTypeId, new { @class = "round-config-lft" })
                @Html.DropDownListFor(m => m.RndTypeId, (SelectList)ViewBag.TRoundType, "--Select--", new { @id = "TReviewRound", @class = "round-slt-lft", @onchange = "CopyRndType(this);" })
            </div>
            @if (RndAttr != BERndAttr.OfferRound)
            {
                <div id="RndConfig">
                    <div class="width-38">
                        @Html.LanguageLabelFor(m => m.RoundWeight, new { @class = "round-config-rgt labelwidth-rgt" })
                        @Html.TextBoxFor(m => m.RoundWeight, new { @class = "round-rgt", @onchange = "CopyRndWeight(this);" })
                    </div>
                    <div class="width-62">
                        @Html.LanguageLabelFor(m => m.PromoteCandidate, new { @class = "round-config-lft " })
                        @Html.DropDownListFor(m => m.PromoteCandidate, (SelectList)ViewBag.YesNoDropDownPromoteCandidate, "- Select -", new { @class = "round-slt-lft" })
                    </div>
                    <div class="width-38">
                        @Html.LanguageLabelFor(m => m.PromotionThresoldScore, new { @class = "round-config-rgt labelwidth-rgt" })
                        @Html.TextBoxFor(m => m.PromotionThresoldScore, new { @class = "round-rgt" })
                    </div>
                </div>
            }
        </div>
        <div class="box" style="border-bottom: 2px solid #953634;">
            <button type="submit" class="prfle-button-save CaseUpper">@Html.LanguageLabel(BECommonConstantConst.FRM_APP_REV_SAVE)</button>
            <button type="button" id="RemoveRound" class="prfle-button-delete CaseUpper" onclick="RemoveTRoundConfig(this);">@Html.LanguageLabel(BECommonConstantConst.FRM_APP_REV_REMOVE)</button>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#TReviewRound').change(function () {
        var TRndTypeId = $(this).val();
        var TVacid = $(this).parents('.RoundConfigNewForm').parent().prev().attr('data-tvacidonly');
        var TVacRndId = $('#TReviewRound').parents(".vacancy-Details").attr('data-tvacrndconfigid');
        var dataLink = '@Html.Raw(@Url.Action("CheckForRoundNo", "TemplateVacancy", new { TRndTypeId = "_TRNDTYPEID_", TVacId  = "_TVACID_",TVacRndId = "_TVACRNDID_"}))';
        dataLink = dataLink.replace("_TRNDTYPEID_", TRndTypeId);
        dataLink = dataLink.replace("_TVACID_", TVacid);
        dataLink = dataLink.replace("_TVACRNDID_", TVacRndId);
        var _ele = $('#frmTVacRoundConfig').find('.accNewReviewRound').children('.acc-Content');
        VacancyModel.CallGetMethod(dataLink, function (data) {
            if (data != "")
                $(".lblRoundWeight").show();
            else
                $(".lblRoundWeight").hide();
            $(_ele).html('');
            $(_ele).append(data);
        });
        CopyRndType(this);
    });

    function CopyRndType(changeVal) {
        var cur = $(changeVal);
        var text = "";
        if (cur.val() != 0) {
            text = cur.find('option:selected').text();
        }
        cur.closest('.acc-Content').prev().attr('data-qdatatype', cur.val());
        VacancyModel.CopyDataToHeader(cur, "lblRndType", text);
    }

    function CopyRndWeight(changeVal) {
        var cur = $(changeVal);
        VacancyModel.CopyDataToHeader(cur, "lblRndWeight", cur.val())
    }

    function RoundSuccess(data, tVacId) {
        
        var _$TVacAcc = $("div[data-tvacidonly='" + tVacId + "']");
        _$TVacAcc = _$TVacAcc.next();
        var JsonData = JSON.parse(data);
        if (!JsonData.IsError) {
            _$TVacAcc.find('.RoundConfigNewForm').html('');
            _$TVacAcc.find('.RoundConfigNewForm').hide();
            var _$jsonData = $('<div>' + JsonData.Data + '</div>');
            _$jsonData.find('.cntRound').text((_$TVacAcc.find('.AccRound > .acc-header').size() + 1).toString());
            _$TVacAcc.find('.AccRound').append(_$jsonData.html()).accordion(VacancyModel.AccFirstAttr).accordion("refresh");
            var Roundcount = _$TVacAcc.find('.AccRound').parent().prev().children('p').find('#vacrndcnt').text();
            var finalcount = parseInt(Roundcount.match(/[0-9]+/)[0], 10) + 1;
            _$TVacAcc.find('.AccRound').parent().prev().children('p').find('#vacrndcnt').text("(Rounds: " + finalcount + ")")
        }
    }

    function RemoveTRoundConfig(element) {
        $(element).closest("form").remove();
        return false;
    }

    function RoundFailure() {
        return false;
    }

</script>

ATS.WebUi/Areas/Employee/Views/TemplateVacancy/Shared/_SectionDone.cshtml
<div style="width: 98%; float:left;" class="content">
    <a class="doneround"><span class="ttldbrown" id="DoneRound" style="font-weight:600;"></span></a>
</div>